### ISSUE TITLE
No source code was seen 

### ISSUE THREAD

**Issue by zitoxxx** [waderwu/extractor-java#2]
No source code was seen and extracted to /Users/xx/Desktop/extractor-java-master/cc-test.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/51818386/175875171-068db90e-7af8-4775-8690-0d62bb9ee70b.png">

**Comment by SuperXiaoxiong** [comment]
也遇到这个问题了，请教一下师傅怎么解决得
